# Generated by Django 2.2.5 on 2019-12-14 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20191213_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portada',
            name='libro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portada', to='inicio.Libro'),
        ),
    ]
