# Generated by Django 2.2.5 on 2019-12-14 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20191214_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial', to='inicio.Libro'),
        ),
    ]
