# Generated by Django 2.2.5 on 2019-12-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20191214_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='libro',
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial', to='inicio.Editorial'),
        ),
    ]
