# Generated by Django 2.2.5 on 2019-12-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_libro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleprestamo',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
