# Generated by Django 2.2.5 on 2019-12-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_auto_20191215_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleprestamo',
            name='fecha_vencimiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='anio_publicacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
